### ISSUE TITLE
Jenkins isn't rebuilding write.status.im

### ISSUE THREAD

**Issue by shamisem** [status-im/write.status.im#33]
**Describe the bug**
Even though everything's okay with the dev-based [dev-write.status.im](https://dev-write.status.im), the master-based website - write.status.im - isn't updating. The master branch is up to date with develop.

Here's a list of my commits: https://github.com/status-im/write.status.im/commits?author=shamisem

Everything I merged after Jan 19 is showing up on dev-write.status.im, but not write.status.im.

An example:
https://github.com/status-im/write.status.im/commit/39d5811e7d0e039a9e775f29830db109cb544514
https://dev-write.status.im/style-conventions/#spelling
https://write.status.im/style-conventions/

The 'Spelling' section is missing on write.status.im, along with several other updates.

At the same time, the infra tool says that everything's fine with the Jenkins job for write.status.im:

<img width="1121" alt="Screenshot 2023-02-20 at 12 21 50" src="https://user-images.githubusercontent.com/30394334/220051176-5ebb9dae-795c-4d1e-931d-24dfb941e595.png">

**Expected behavior**
write.status.im is updated whenever we push any changes to master.

**Comment by jakubgs** [comment]
That's because the webhook for updating the hosted site doesn't exist:

![image](https://user-images.githubusercontent.com/2212681/220056921-8f0fe70c-a890-43a7-81d4-abb532d6fc6b.png)

Just the one for CI exists.

**Comment by jakubgs** [comment]
Now it looks correct:

![image](https://user-images.githubusercontent.com/2212681/220057201-e55d2ae0-4170-432a-853e-fb478d347936.png)

No idea why it disappeared.

**Comment by jakubgs** [comment]
Site should be updated now.
